---
title: "Find Bias Features"
author: 
  - name: Christine Hou
    affiliation: "Johns Hopkins Bloomberg School of Public Health, 
    Baltimore, MD, USA"
    email: chris2018hou@gmail.com
  - name: Jacqui Thompson
    affiliation: "Johns Hopkins Bloomberg School of Public Health, 
    Baltimore, MD, USA"
    email: jthom338@jh.edu
  - name: Stephanie C. Hicks
    affiliation: "Johns Hopkins Bloomberg School of Public Health, 
    Baltimore, MD, USA"
    email: shicks19@jhu.edu
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    self_contained: yes
    css: header-styles.css
    highlight: pygments
    style: symbol
    df_print: kable
package: "BiasDetect"
vignette: >
  %\VignetteIndexEntry{Find Bias Genes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```


# Installation

`BiasDetect` is a R package. Install development version from
[GitHub](https://christinehou11.github.io/BiasDetect):

```{r 'install dev', eval = FALSE}
remotes::install("christinehou11/BiasDetect")
```

# Basic User Guide

## Load Necessary Packages

Install additional required packages before running package codes.

```{r 'pkg install', eval=FALSE}
pkgs <- c("dplyr", "tidyr", "scran", "scry", "nnSVG")
required_pkgs <- pkgs[!pkgs %in% rownames(installed.packages())]
BiocManager::install(required_pkgs)
```

Load additional packages. `dplyr` package is widely used in this vignettes to
conduct data wrangling and specific information extraction.

```{r 'library', message=FALSE}
library(BiasDetect)
```


# `R` session information {.unnumbered}

```{r 'sessionInfo', echo=FALSE}
## Session info
options(width = 120)
sessionInfo()
```
